osx_image: xcode7.3
language: objective-c
xcode_project: ImageCoordinateSpace.xcodeproj
xcode_scheme: ImageCoordinateSpace
xcode_sdk: iphonesimulator
cache:
  bundler: true
  directories:
    - Carthage/Build/iOS
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - ls -la Carthage/Build/iOS/?*.framework || carthage bootstrap --platform iOS
script:
  - xctool test
