osx_image: xcode7.2
language: objective-c
xcode_project: ImageCoordinateSpace.xcodeproj
xcode_scheme: ImageCoordinateSpace
xcode_sdk: iphonesimulator9.2
cache:
  bundler: true
  directories:
    - Carthage/Build/iOS
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - ls -la Carthage/Build/iOS/?*.framework || carthage bootstrap --platform iOS
before_deploy:
  - carthage build --no-skip-current
  - carthage archive ImageCoordinateSpace
deploy:
  provider: releases
  file: ImageCoordinateSpace.framework.zip
  on:
    tags:true
